import type {
  Appointment,
  BillingRecord,
  Department,
  Doctor,
  Hospital,
  Patient,
  Prescription,
  Room,
  User,
} from "./types";

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: "h1",
    name: "City General Hospital",
    address: "123 Main St, Chicago, IL 60601",
    contact: "555-0100",
    status: "active",
    createdAt: "2020-01-15",
  },
  {
    id: "h2",
    name: "Metro Health Center",
    address: "456 Oak Ave, New York, NY 10001",
    contact: "555-0200",
    status: "active",
    createdAt: "2021-03-22",
  },
  {
    id: "h3",
    name: "Riverside Medical",
    address: "789 River Rd, Los Angeles, CA 90001",
    contact: "555-0300",
    status: "inactive",
    createdAt: "2019-07-08",
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "u0",
    name: "Platform Admin",
    role: "superAdmin",
    email: "superadmin@medcore.dev",
  },
  {
    id: "u1",
    name: "Dr. Evelyn Reed",
    role: "admin",
    email: "admin@medicore.com",
    specialty: "Administration",
    hospitalId: "h1",
  },
  {
    id: "u2",
    name: "Dr. Marcus Chen",
    role: "doctor",
    email: "mchen@medicore.com",
    specialty: "Cardiology",
    department: "Cardiology",
    hospitalId: "h1",
  },
  {
    id: "u3",
    name: "Sarah Johnson",
    role: "receptionist",
    email: "sjohnson@medicore.com",
    hospitalId: "h1",
  },
  {
    id: "u4",
    name: "James Wilson",
    role: "patient",
    email: "jwilson@medicore.com",
    hospitalId: "h1",
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Marcus Chen",
    specialty: "Cardiology",
    department: "Cardiology",
    phone: "+1 555-0101",
    email: "mchen@medicore.com",
    status: "Active",
    patients: 24,
    experience: 12,
  },
  {
    id: "d2",
    name: "Dr. Priya Sharma",
    specialty: "Neurology",
    department: "Neurology",
    phone: "+1 555-0102",
    email: "psharma@medicore.com",
    status: "Busy",
    patients: 18,
    experience: 9,
  },
  {
    id: "d3",
    name: "Dr. Robert Halen",
    specialty: "Orthopedics",
    department: "Orthopedics",
    phone: "+1 555-0103",
    email: "rhalen@medicore.com",
    status: "Active",
    patients: 31,
    experience: 15,
  },
  {
    id: "d4",
    name: "Dr. Amelia Gbana",
    specialty: "Pediatrics",
    department: "Pediatrics",
    phone: "+1 555-0104",
    email: "agbana@medicore.com",
    status: "On Leave",
    patients: 0,
    experience: 7,
  },
  {
    id: "d5",
    name: "Dr. Thomas Wren",
    specialty: "General Surgery",
    department: "Surgery",
    phone: "+1 555-0105",
    email: "twren@medicore.com",
    status: "Active",
    patients: 14,
    experience: 20,
  },
  {
    id: "d6",
    name: "Dr. Lydia Park",
    specialty: "Dermatology",
    department: "Dermatology",
    phone: "+1 555-0106",
    email: "lpark@medicore.com",
    status: "Active",
    patients: 22,
    experience: 8,
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "Evelyn Reed",
    age: 45,
    gender: "Female",
    phone: "+1 555-1001",
    email: "ereed@email.com",
    bloodGroup: "A+",
    condition: "Cardiac Arrhythmia",
    status: "Admitted",
    admittedDate: "2026-05-10",
    doctorId: "d1",
    address: "123 Maple St, Chicago",
    emergencyContact: "+1 555-9001",
  },
  {
    id: "p2",
    name: "Kenny Smith",
    age: 32,
    gender: "Male",
    phone: "+1 555-1002",
    email: "ksmith@email.com",
    bloodGroup: "O+",
    condition: "Fractured Femur",
    status: "Discharged",
    admittedDate: "2026-05-09",
    doctorId: "d3",
    address: "456 Oak Ave, Chicago",
    emergencyContact: "+1 555-9002",
  },
  {
    id: "p3",
    name: "John Williams",
    age: 58,
    gender: "Male",
    phone: "+1 555-1003",
    email: "jwilliams@email.com",
    bloodGroup: "B-",
    condition: "Hypertension",
    status: "In-Progress",
    admittedDate: "2026-05-13",
    doctorId: "d1",
    address: "789 Pine Rd, Chicago",
    emergencyContact: "+1 555-9003",
  },
  {
    id: "p4",
    name: "Cata Rhonn",
    age: 27,
    gender: "Female",
    phone: "+1 555-1004",
    email: "crhonn@email.com",
    bloodGroup: "AB+",
    condition: "Migraine Cluster",
    status: "Discharged",
    admittedDate: "2026-04-25",
    doctorId: "d2",
    address: "321 Elm St, Chicago",
    emergencyContact: "+1 555-9004",
  },
  {
    id: "p5",
    name: "Michael Torres",
    age: 63,
    gender: "Male",
    phone: "+1 555-1005",
    email: "mtorres@email.com",
    bloodGroup: "A-",
    condition: "Knee Replacement",
    status: "Admitted",
    admittedDate: "2026-05-14",
    doctorId: "d3",
    address: "654 Birch Ln, Chicago",
    emergencyContact: "+1 555-9005",
  },
  {
    id: "p6",
    name: "Asha Patel",
    age: 39,
    gender: "Female",
    phone: "+1 555-1006",
    email: "apatel@email.com",
    bloodGroup: "O-",
    condition: "Appendectomy",
    status: "Admitted",
    admittedDate: "2026-05-15",
    doctorId: "d5",
    address: "987 Cedar Ave, Chicago",
    emergencyContact: "+1 555-9006",
  },
  {
    id: "p7",
    name: "David Nguyen",
    age: 11,
    gender: "Male",
    phone: "+1 555-1007",
    email: "dnguyen@email.com",
    bloodGroup: "B+",
    condition: "Bronchitis",
    status: "Scheduled",
    admittedDate: "2026-05-16",
    doctorId: "d4",
    address: "147 Walnut Rd, Chicago",
    emergencyContact: "+1 555-9007",
  },
  {
    id: "p8",
    name: "Lena Fischer",
    age: 51,
    gender: "Female",
    phone: "+1 555-1008",
    email: "lfischer@email.com",
    bloodGroup: "A+",
    condition: "Eczema Treatment",
    status: "Scheduled",
    admittedDate: "2026-05-16",
    doctorId: "d6",
    address: "258 Poplar St, Chicago",
    emergencyContact: "+1 555-9008",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Evelyn Reed",
    doctorId: "d1",
    doctorName: "Dr. Marcus Chen",
    date: "2026-05-16",
    time: "09:00",
    type: "Follow-up",
    status: "Confirmed",
    token: 1,
  },
  {
    id: "a2",
    patientId: "p3",
    patientName: "John Williams",
    doctorId: "d1",
    doctorName: "Dr. Marcus Chen",
    date: "2026-05-16",
    time: "09:30",
    type: "Consultation",
    status: "Checked-In",
    token: 2,
  },
  {
    id: "a3",
    patientId: "p5",
    patientName: "Michael Torres",
    doctorId: "d3",
    doctorName: "Dr. Robert Halen",
    date: "2026-05-16",
    time: "10:00",
    type: "Post-Op",
    status: "Scheduled",
    token: 3,
  },
  {
    id: "a4",
    patientId: "p6",
    patientName: "Asha Patel",
    doctorId: "d5",
    doctorName: "Dr. Thomas Wren",
    date: "2026-05-16",
    time: "10:30",
    type: "Emergency",
    status: "Confirmed",
    token: 4,
  },
  {
    id: "a5",
    patientId: "p7",
    patientName: "David Nguyen",
    doctorId: "d4",
    doctorName: "Dr. Amelia Gbana",
    date: "2026-05-16",
    time: "11:00",
    type: "Consultation",
    status: "Scheduled",
    token: 5,
  },
  {
    id: "a6",
    patientId: "p8",
    patientName: "Lena Fischer",
    doctorId: "d6",
    doctorName: "Dr. Lydia Park",
    date: "2026-05-16",
    time: "11:30",
    type: "Check-up",
    status: "Scheduled",
    token: 6,
  },
  {
    id: "a7",
    patientId: "p2",
    patientName: "Kenny Smith",
    doctorId: "d3",
    doctorName: "Dr. Robert Halen",
    date: "2026-05-17",
    time: "14:00",
    type: "Follow-up",
    status: "Completed",
    token: 7,
  },
  {
    id: "a8",
    patientId: "p4",
    patientName: "Cata Rhonn",
    doctorId: "d2",
    doctorName: "Dr. Priya Sharma",
    date: "2026-05-17",
    time: "15:00",
    type: "Follow-up",
    status: "Completed",
    token: 8,
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: "dep1",
    name: "Cardiology",
    head: "Dr. Marcus Chen",
    doctors: 4,
    patients: 28,
    rooms: 12,
    status: "Active",
  },
  {
    id: "dep2",
    name: "Neurology",
    head: "Dr. Priya Sharma",
    doctors: 3,
    patients: 19,
    rooms: 8,
    status: "Active",
  },
  {
    id: "dep3",
    name: "Orthopedics",
    head: "Dr. Robert Halen",
    doctors: 5,
    patients: 35,
    rooms: 14,
    status: "Full",
  },
  {
    id: "dep4",
    name: "Pediatrics",
    head: "Dr. Amelia Gbana",
    doctors: 4,
    patients: 22,
    rooms: 10,
    status: "Active",
  },
  {
    id: "dep5",
    name: "General Surgery",
    head: "Dr. Thomas Wren",
    doctors: 6,
    patients: 18,
    rooms: 16,
    status: "Active",
  },
  {
    id: "dep6",
    name: "Dermatology",
    head: "Dr. Lydia Park",
    doctors: 2,
    patients: 14,
    rooms: 6,
    status: "Active",
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "r1",
    number: "ICU-01",
    type: "ICU",
    floor: 1,
    patientId: "p1",
    patientName: "Evelyn Reed",
    status: "Occupied",
  },
  { id: "r2", number: "ICU-02", type: "ICU", floor: 1, status: "Available" },
  {
    id: "r3",
    number: "ICU-03",
    type: "ICU",
    floor: 1,
    patientId: "p6",
    patientName: "Asha Patel",
    status: "Occupied",
  },
  {
    id: "r4",
    number: "G-101",
    type: "General",
    floor: 1,
    patientId: "p3",
    patientName: "John Williams",
    status: "Occupied",
  },
  { id: "r5", number: "G-102", type: "General", floor: 1, status: "Available" },
  {
    id: "r6",
    number: "G-103",
    type: "General",
    floor: 1,
    status: "Maintenance",
  },
  {
    id: "r7",
    number: "P-201",
    type: "Private",
    floor: 2,
    patientId: "p5",
    patientName: "Michael Torres",
    status: "Occupied",
  },
  { id: "r8", number: "P-202", type: "Private", floor: 2, status: "Available" },
  {
    id: "r9",
    number: "SP-301",
    type: "Semi-Private",
    floor: 3,
    status: "Available",
  },
  {
    id: "r10",
    number: "SP-302",
    type: "Semi-Private",
    floor: 3,
    status: "Available",
  },
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: "rx1",
    patientId: "p1",
    patientName: "Evelyn Reed",
    doctorId: "d1",
    doctorName: "Dr. Marcus Chen",
    date: "2026-05-15",
    diagnosis: "Cardiac Arrhythmia — rate control required",
    medicines: [
      {
        name: "Metoprolol 50mg",
        dosage: "1 tablet",
        frequency: "Twice daily",
        duration: "30 days",
      },
      {
        name: "Aspirin 81mg",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "60 days",
      },
    ],
    notes: "Avoid strenuous activity. Return in 2 weeks for ECG.",
  },
  {
    id: "rx2",
    patientId: "p3",
    patientName: "John Williams",
    doctorId: "d1",
    doctorName: "Dr. Marcus Chen",
    date: "2026-05-14",
    diagnosis: "Hypertension Stage 2",
    medicines: [
      {
        name: "Amlodipine 10mg",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "90 days",
      },
      {
        name: "Lisinopril 20mg",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "90 days",
      },
    ],
    notes: "Low sodium diet. Monitor BP daily.",
  },
];

export const MOCK_BILLING: BillingRecord[] = [
  {
    id: "b1",
    patientId: "p2",
    patientName: "Kenny Smith",
    date: "2026-05-15",
    consultationFee: 150,
    labCharges: 320,
    medicineCharges: 85,
    roomCharges: 800,
    total: 1355,
    status: "Paid",
    paymentMethod: "Card",
  },
  {
    id: "b2",
    patientId: "p4",
    patientName: "Cata Rhonn",
    date: "2026-05-14",
    consultationFee: 120,
    labCharges: 180,
    medicineCharges: 65,
    roomCharges: 400,
    total: 765,
    status: "Paid",
    paymentMethod: "UPI",
  },
  {
    id: "b3",
    patientId: "p1",
    patientName: "Evelyn Reed",
    date: "2026-05-10",
    consultationFee: 200,
    labCharges: 540,
    medicineCharges: 120,
    roomCharges: 2400,
    total: 3260,
    status: "Pending",
  },
  {
    id: "b4",
    patientId: "p5",
    patientName: "Michael Torres",
    date: "2026-05-14",
    consultationFee: 250,
    labCharges: 400,
    medicineCharges: 200,
    roomCharges: 1200,
    total: 2050,
    status: "Partial",
    paymentMethod: "Insurance",
  },
  {
    id: "b5",
    patientId: "p3",
    patientName: "John Williams",
    date: "2026-05-13",
    consultationFee: 150,
    labCharges: 220,
    medicineCharges: 95,
    roomCharges: 600,
    total: 1065,
    status: "Pending",
  },
];

export const STATS = {
  admissionsToday: 13,
  activeAppointments: 20,
  revenueThisMonth: 108722,
  availableDoctors: 35,
  totalPatients: 284,
  bedsOccupied: 6,
  bedsTotal: 10,
};
