/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Hospital {
  'id' : string,
  'status' : HospitalStatus,
  'contact' : string,
  'name' : string,
  'createdAt' : bigint,
  'logoUri' : string,
  'address' : string,
}
export interface HospitalAdmin {
  'id' : string,
  'status' : HospitalAdminStatus,
  'username' : string,
  'name' : string,
  'email' : string,
  'hospitalId' : string,
}
export type HospitalAdminStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Suspended' : null };
export type HospitalStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface _SERVICE {
  'create_hospital' : ActorMethod<[string, string, string], Hospital>,
  'create_hospital_admin' : ActorMethod<
    [string, string, string, string],
    HospitalAdmin
  >,
  'get_hospital_admins' : ActorMethod<[string], Array<HospitalAdmin>>,
  'get_hospital_by_id' : ActorMethod<[string], [] | [Hospital]>,
  'get_hospitals' : ActorMethod<[], Array<Hospital>>,
  'update_hospital' : ActorMethod<
    [string, string, string, string, HospitalStatus],
    [] | [Hospital]
  >,
  'update_hospital_admin_status' : ActorMethod<
    [string, HospitalAdminStatus],
    [] | [HospitalAdmin]
  >,
  'verify_super_admin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];