/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HospitalStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'status' : HospitalStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'logoUri' : IDL.Text,
  'address' : IDL.Text,
});
export const HospitalAdminStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
});
export const HospitalAdmin = IDL.Record({
  'id' : IDL.Text,
  'status' : HospitalAdminStatus,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'hospitalId' : IDL.Text,
});

export const idlService = IDL.Service({
  'create_hospital' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Hospital], []),
  'create_hospital_admin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [HospitalAdmin],
      [],
    ),
  'get_hospital_admins' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HospitalAdmin)],
      ['query'],
    ),
  'get_hospital_by_id' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
  'get_hospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'update_hospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, HospitalStatus],
      [IDL.Opt(Hospital)],
      [],
    ),
  'update_hospital_admin_status' : IDL.Func(
      [IDL.Text, HospitalAdminStatus],
      [IDL.Opt(HospitalAdmin)],
      [],
    ),
  'verify_super_admin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HospitalStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'status' : HospitalStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'logoUri' : IDL.Text,
    'address' : IDL.Text,
  });
  const HospitalAdminStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const HospitalAdmin = IDL.Record({
    'id' : IDL.Text,
    'status' : HospitalAdminStatus,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'hospitalId' : IDL.Text,
  });
  
  return IDL.Service({
    'create_hospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Hospital],
        [],
      ),
    'create_hospital_admin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [HospitalAdmin],
        [],
      ),
    'get_hospital_admins' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HospitalAdmin)],
        ['query'],
      ),
    'get_hospital_by_id' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
    'get_hospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'update_hospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, HospitalStatus],
        [IDL.Opt(Hospital)],
        [],
      ),
    'update_hospital_admin_status' : IDL.Func(
        [IDL.Text, HospitalAdminStatus],
        [IDL.Opt(HospitalAdmin)],
        [],
      ),
    'verify_super_admin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };