/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Hospital {
    id: string;
    status: HospitalStatus;
    contact: string;
    name: string;
    createdAt: bigint;
    logoUri: string;
    address: string;
}
export interface HospitalAdmin {
    id: string;
    status: HospitalAdminStatus;
    username: string;
    name: string;
    email: string;
    hospitalId: string;
}
export enum HospitalAdminStatus {
    Inactive = "Inactive",
    Active = "Active",
    Suspended = "Suspended"
}
export enum HospitalStatus {
    Inactive = "Inactive",
    Active = "Active"
}
export interface backendInterface {
    create_hospital(name: string, address: string, contact: string): Promise<Hospital>;
    create_hospital_admin(hospitalId: string, username: string, name: string, email: string): Promise<HospitalAdmin>;
    get_hospital_admins(hospitalId: string): Promise<Array<HospitalAdmin>>;
    get_hospital_by_id(id: string): Promise<Hospital | null>;
    get_hospitals(): Promise<Array<Hospital>>;
    update_hospital(id: string, name: string, address: string, contact: string, status: HospitalStatus): Promise<Hospital | null>;
    update_hospital_admin_status(id: string, status: HospitalAdminStatus): Promise<HospitalAdmin | null>;
    verify_super_admin(username: string, password: string): Promise<boolean>;
}
import type { Hospital as _Hospital, HospitalAdmin as _HospitalAdmin, HospitalAdminStatus as _HospitalAdminStatus, HospitalStatus as _HospitalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async create_hospital(arg0: string, arg1: string, arg2: string): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.create_hospital(arg0, arg1, arg2);
                return from_candid_Hospital_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_hospital(arg0, arg1, arg2);
            return from_candid_Hospital_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async create_hospital_admin(arg0: string, arg1: string, arg2: string, arg3: string): Promise<HospitalAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.create_hospital_admin(arg0, arg1, arg2, arg3);
                return from_candid_HospitalAdmin_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_hospital_admin(arg0, arg1, arg2, arg3);
            return from_candid_HospitalAdmin_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_hospital_admins(arg0: string): Promise<Array<HospitalAdmin>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_hospital_admins(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_hospital_admins(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_hospital_by_id(arg0: string): Promise<Hospital | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_hospital_by_id(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_hospital_by_id(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_hospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_hospitals();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_hospitals();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_hospital(arg0: string, arg1: string, arg2: string, arg3: string, arg4: HospitalStatus): Promise<Hospital | null> {
        if (this.processError) {
            try {
                const result = await this.actor.update_hospital(arg0, arg1, arg2, arg3, to_candid_HospitalStatus_n12(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_hospital(arg0, arg1, arg2, arg3, to_candid_HospitalStatus_n12(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_hospital_admin_status(arg0: string, arg1: HospitalAdminStatus): Promise<HospitalAdmin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.update_hospital_admin_status(arg0, to_candid_HospitalAdminStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_hospital_admin_status(arg0, to_candid_HospitalAdminStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async verify_super_admin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verify_super_admin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verify_super_admin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_HospitalAdminStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HospitalAdminStatus): HospitalAdminStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_HospitalAdmin_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HospitalAdmin): HospitalAdmin {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_HospitalStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HospitalStatus): HospitalStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Hospital_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hospital): Hospital {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hospital]): Hospital | null {
    return value.length === 0 ? null : from_candid_Hospital_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HospitalAdmin]): HospitalAdmin | null {
    return value.length === 0 ? null : from_candid_HospitalAdmin_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _HospitalStatus;
    contact: string;
    name: string;
    createdAt: bigint;
    logoUri: string;
    address: string;
}): {
    id: string;
    status: HospitalStatus;
    contact: string;
    name: string;
    createdAt: bigint;
    logoUri: string;
    address: string;
} {
    return {
        id: value.id,
        status: from_candid_HospitalStatus_n3(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        name: value.name,
        createdAt: value.createdAt,
        logoUri: value.logoUri,
        address: value.address
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _HospitalAdminStatus;
    username: string;
    name: string;
    email: string;
    hospitalId: string;
}): {
    id: string;
    status: HospitalAdminStatus;
    username: string;
    name: string;
    email: string;
    hospitalId: string;
} {
    return {
        id: value.id,
        status: from_candid_HospitalAdminStatus_n7(_uploadFile, _downloadFile, value.status),
        username: value.username,
        name: value.name,
        email: value.email,
        hospitalId: value.hospitalId
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
}): HospitalStatus {
    return "Inactive" in value ? HospitalStatus.Inactive : "Active" in value ? HospitalStatus.Active : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Suspended: null;
}): HospitalAdminStatus {
    return "Inactive" in value ? HospitalAdminStatus.Inactive : "Active" in value ? HospitalAdminStatus.Active : "Suspended" in value ? HospitalAdminStatus.Suspended : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hospital>): Array<Hospital> {
    return value.map((x)=>from_candid_Hospital_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HospitalAdmin>): Array<HospitalAdmin> {
    return value.map((x)=>from_candid_HospitalAdmin_n5(_uploadFile, _downloadFile, x));
}
function to_candid_HospitalAdminStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalAdminStatus): _HospitalAdminStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_HospitalStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalStatus): _HospitalStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalStatus): {
    Inactive: null;
} | {
    Active: null;
} {
    return value == HospitalStatus.Inactive ? {
        Inactive: null
    } : value == HospitalStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalAdminStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    Suspended: null;
} {
    return value == HospitalAdminStatus.Inactive ? {
        Inactive: null
    } : value == HospitalAdminStatus.Active ? {
        Active: null
    } : value == HospitalAdminStatus.Suspended ? {
        Suspended: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
